spring:
  # dev-tools
  devtools:
    restart:
      enabled: true

  # database
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backend_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: LXY20050720

  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      # Lettuce pool
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms

#JWT
jwt:
  secret: mySecretKeyThatIsLongEnough32Bytes_ChangeMeInProduction
  expiration: 2592000000 # 单位是秒，即 30天

# MyBatis Plus Log
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

wechat:
  # 公众号或开放平台应用的唯一标识
  app-id: your-wechat-app-id
  # 应用的密钥
  secret: your-wechat-secret